FROM eejay73/codenvy-ws-base:python3.6.5

## Default pip installs

RUN sudo pip install autopep8 && sudo pip install django

## Default port for python apps
##  Use 'http://${server.port.8081}' in Che command preview macro
EXPOSE 8081
